Refactor SootUp module structure
soot-oss/SootUp pull request #1049
Opened 2024-08-30 09:31 UTC by stschott

- Separate sootup.analysis into sootup.analysis.interprocedural and sootup.analysis.intraprocedural
- Separate body interceptors from sootup.java.core into new module sootup.interceptors
- Move Dex interceptors into sootup.apk.parser
- Add new modules to report and DependencyManagement section in root pom.xml

2024-08-30 13:47 UTC, JonasKlauke requested changes

2024-08-30 13:47 UTC, JonasKlauke commented on sootup.analysis.intraprocedural/pom.xml
> +            <artifactId>junit-jupiter-api</artifactId>
here it is missing the test scope

2024-08-30 13:47 UTC, JonasKlauke commented on sootup.analysis.intraprocedural/pom.xml
> +            <id>sonatype-snapshots</id>
why do we need the snapshot repo?

2024-08-30 13:47 UTC, JonasKlauke commented on sootup.apk.parser/src/main/java/interceptors/AbstractNullTransformer.java
> +package interceptors;
the package should be sootup.apk.parser.interceptors.

2024-08-30 13:49 UTC, JonasKlauke commented
I think we should also rename sootup.apk.parser and sootup.jimple.parser and drop the parser part

2024-09-02 09:34 UTC, swissiety commented
> I think we should also rename sootup.apk.parser and sootup.jimple.parser and drop the parser part

Then we should split the concrete Jimple Implementations from core and only keep interfaces there.

2024-09-05 11:37 UTC, JonasKlauke approved these changes

2024-09-13 08:15 UTC, merged