Create SootClass builder
soot-oss/SootUp pull request #1069
Opened 2024-09-13 14:51 UTC by wkktoria

As described in #1059, I've created a builder for `SootClass` which is based on `SootMethod` and `SootField`'s builders.

2024-09-16 08:49 UTC, swissiety approved these changes
thanks for your contribution! If you like to, we would really appreciate if you could do the same for the OverridingClassSource / OverridingMethodSource so SootUp can have a testcase demonstrating the usage.

2024-09-16 14:29 UTC, wkktoria commented
Sure, I'll work on making changes to these as well.

2024-09-18 12:22 UTC, swissiety requested changes
Thank you! As we want to create a complete OverridingClassSource making use of multiple methods at once please return the different interfaces (as an accumulated interface/step) from the with* methods (e.g. see https://www.svlada.com/step-builder-pattern/).
(applies to both of the added Builders)

We even could think about extending the API of withMethods(Set<SootMethods> )/ withFields(Set<SootFields>) methods to singular withField(SootField) and collect the parameters on our own.

2024-09-18 16:37 UTC, wkktoria commented
I've changed the builders to use different interfaces as suggested, but I am not sure how to replace these methods with singular one.

2024-10-03 13:02 UTC, T0niKroOs commented
Thank you for the clarification! I'm looking forward to the release of the new features.

2025-03-07 08:54 UTC, closed without merging