repair ssa
soot-oss/SootUp pull request #1104
Opened 2024-10-09 14:39 UTC by wangzun66

- [x]  check and arrange classes for block order
- [ ]  repair and dominance finder 
- [ ]  check ssa

2024-10-31 02:24 UTC, Liyw979 commented
Hi wangzun66, thanks for you work. I hope to provide some failing test cases
```
      PathBasedAnalysisInputLocation.create(
        path,
        SourceType.Application,
        java.util.List.of(StaticSingleAssignmentFormer())
      )
```
code
```
import java.io.*;
class Main {
    public static void main(String[] args) throws IOException {
        byte[] data;
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            output.write(args[0].getBytes("UTF-8"));
            data = output.toByteArray();
        }
        System.out.println(new String(data, "UTF-8"));
    }
}
```
error message: 
```
Caused by: java.lang.RuntimeException: The given block: Block [$stack11 := @caughtexception, l3 = $stack11] is not in BlockGraph!
	at sootup.core.graph.DominanceFinder.getDominanceFrontiers(DominanceFinder.java:167)
```

2024-10-31 02:27 UTC, Liyw979 commented
code
```
class Test {
    public static void main(String[] args) {
        String input = "";
        for (int i = 0; i < args.length; i++) {
            input = input + args[i];
        }
        System.out.println(input);
    }
}
```
error message
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at sootup.interceptors.StaticSingleAssignmentFormer.addPhiStmts(StaticSingleAssignmentFormer.java:309)
```

2024-10-31 08:13 UTC, wangzun66 commented
@Liyw979  OK, I will do them later.

2024-11-06 11:30 UTC, wangzun66 commented
@Liyw979 SSA should work on your provided test cases. Thanks for your information. If you find any errors in SSA, please feel free to point them out. Thank you!

2024-11-06 12:55 UTC, Liyw979 commented
@wangzun66 Thank you! I will do some tests tomorrow.

2024-11-07 02:41 UTC, Liyw979 commented
I found some failing cases like 
```
import java.io.*;
class Main {
    public static void main(String[] args) throws IOException {
        byte[] data;
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            output.write(args[0].getBytes("UTF-8"));
            data = output.toByteArray();
        }
        System.out.println(new String(data, "UTF-8"));
    }
}
```
```
Caused by: java.lang.RuntimeException: The given block: Block [$stack11 := @caughtexception, l3 = $stack11] is not in BlockGraph!
```

2024-11-07 02:44 UTC, Liyw979 commented
I would recommend collecting some oss package like log4j and run ssa through all methods to see if any method goes wrong.

2024-11-07 02:47 UTC, Liyw979 commented
Also, I notice that some tests runs well with 
```scala
      PathBasedAnalysisInputLocation.create(
        dir.toJava.toPath,
        SourceType.Application,
        java.util.List.of(StaticSingleAssignmentFormer())
      )
```
but failed with
```scala
      PathBasedAnalysisInputLocation.create(
        dir.toJava.toPath,
        SourceType.Application,
         (BytecodeBodyInterceptors.Default.getBodyInterceptors.asScala :+ StaticSingleAssignmentFormer()).asJava
      )
```

2025-01-13 14:24 UTC, swissiety requested changes
please add a short summary as javadoc what each new/changed class is used for

2025-01-13 14:24 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/graph/BlockTraversal.java
> +public interface BlockTraversal {}
```suggestion
public interface BlockTraversalStrategy {}
```

2025-01-13 14:24 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/graph/BlockTraversal.java
> +public interface BlockTraversal {}
please add short javadoc

2025-01-13 14:24 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/graph/BlockIterator.java
> +public interface BlockIterator extends Iterator<BasicBlock<?>> {}
please add a short javadoc

2025-01-17 08:44 UTC, swissiety approved these changes

2025-01-17 08:44 UTC, merged