1110 bug jimple frontend does not apply specified interceptors
soot-oss/SootUp pull request #1123
Opened 2024-10-31 10:04 UTC by sahilagichani14

2024-11-04 11:11 UTC, stschott submitted a review, later dismissed

2024-11-04 11:11 UTC, stschott commented on sootup.jimple.frontend/pom.xml
> +            <artifactId>sootup.interceptors</artifactId>
This can be a test dependency.

2024-11-04 11:11 UTC, stschott commented on sootup.jimple.frontend/src/main/java/sootup/jimple/frontend/JimpleConverter.java
> +      @Nonnull View view) {
Why is View declared as `@Nonnull` if you pass `null` into it? Also instead of changing the method signature, can we add an overloading method that has a `View` parameter?

2024-11-04 11:11 UTC, stschott commented on sootup.jimple.frontend/src/main/java/sootup/jimple/frontend/JimpleConverter.java
> +    return run(parser, inputlocation, sourcePath, Collections.emptyList(), null);
With an overloaded method, we can avoid having to pass `null` all the time.

2024-11-04 11:11 UTC, stschott commented on sootup.jimple.frontend/src/main/java/sootup/jimple/frontend/JimpleStringAnalysisInputLocation.java
> +              CharStreams.fromString(jimpleFileContents), this, path, bodyInterceptors, null);
Same thing here.

2024-11-04 14:53 UTC, stschott commented on sootup.jimple.frontend/src/main/java/sootup/jimple/frontend/JimpleStringAnalysisInputLocation.java
> +              new JimpleView(this));
Why are we creating a new JimpleView here? We shouldn't do this in the InputLocations.

2024-11-15 12:41 UTC, swissiety requested changes

2024-11-15 12:41 UTC, swissiety commented on sootup.jimple.frontend/src/test/java/sootup/jimple/frontend/JimpleStringAnalysisInputLocationTest.java
> +                view.getClassTypes(analysisInputLocation).get(),
please remove that method and use:
```suggestion
                view.getIdentifierFactory().getClassType("package.CLASS")
```

2024-11-15 13:21 UTC, swissiety approved these changes

2024-11-15 13:22 UTC, merged