add failing test case
soot-oss/SootUp pull request #1125
Opened 2024-11-01 19:40 UTC by sahilagichani14

2025-01-06 12:49 UTC, swissiety requested changes

2025-01-06 12:49 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/util/printer/BlockGraphIteratorAndTrapAggregator.java
> +  BasicBlock<?> lastIteratedBlock; // dummy value to remove n-1 unnecessary null-checks
lets remove that comment

2025-01-06 12:49 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/util/printer/LabeledStmtPrinter.java
> +    final Collection<Stmt> targetStmtsOfBranches = getLabeledStmts(stmtGraph, traps);
lets rename targetStmtsOfBranches to labeledStmts

2025-01-06 12:49 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/util/printer/LabeledStmtPrinter.java
> +
seems complicated - Isn't it only necessary to add a `JNopStmt` as the last stmt (i.e. once)?
and it seems this JNopStmt would not be added to labelStmts in line 141

2025-01-06 13:08 UTC, sahilagichani14 commented on sootup.core/src/main/java/sootup/core/util/printer/LabeledStmtPrinter.java
> +
Since we have separate trapStmts in which we already added nop stmt (when we create a nop stmt). To add that same nop stmt as a separate labeledStmt, I'm trying to find that specific nop stmt in targetStmtsOfBranches. Because in one of the test case there were couple of Nop stmts which we can't distinguish so that's the reason I added a for loop and see nop stmt which is in trapStmts.

2025-01-06 13:18 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/util/printer/LabeledStmtPrinter.java
> +
at least from my understanding we only need to insert a JNopStmt once - even when multiple `Trap` objects would reference it as this additional Nop is only needed as a final Stmt - in the other scenarios there is a following Block that can be serialized after the current Block and therefore we can reference that following blocks headStmt.

2025-01-06 13:43 UTC, sahilagichani14 commented on sootup.core/src/main/java/sootup/core/util/printer/LabeledStmtPrinter.java
> +
Yes the Nop stmt added at last is the only inserted JNopStmt once - even when multiple Trap objects would reference it as this additional Nop is only needed as a final Stmt. But if StmtGraph already contains nop stmts then to distinguish  those with this trap nop stmt I'm checking only in trapStmts

2025-01-08 13:04 UTC, swissiety approved these changes

2025-01-08 13:04 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/graph/StmtGraph.java
> +  public final BriefStmtPrinter briefStmtPrinter = new BriefStmtPrinter();
please dont

2025-01-08 13:10 UTC, sahilagichani14 commented on sootup.core/src/main/java/sootup/core/graph/StmtGraph.java
> +  public final BriefStmtPrinter briefStmtPrinter = new BriefStmtPrinter();
Idk why it's still there, There's just one in toString new JimplePrinter().printTo(this, writerOut);

2025-01-08 15:32 UTC, merged

2025-01-08 15:36 UTC, sahilagichani14 commented on sootup.core/src/main/java/sootup/core/graph/StmtGraph.java
> +  public final BriefStmtPrinter briefStmtPrinter = new BriefStmtPrinter();
removed fields and used them directly