Failed jars branch 20241014
soot-oss/SootUp pull request #1146
Opened 2024-12-12 12:59 UTC by sahilagichani14

2024-12-19 08:33 UTC, stschott requested changes

2024-12-19 08:33 UTC, stschott commented on metadata/metadata.json
> +}
This file should be removed before merging.

2024-12-19 08:33 UTC, stschott commented on sootup.java.bytecode.frontend/src/test/resources/jar_failure.json
> +]
This file should also be removed before merging.

2024-12-19 08:33 UTC, stschott commented on sootup.java.bytecode.frontend/src/test/java/sootup/java/bytecode/frontend/inputlocation/FixJars.java
> +  }
Please extract and isolate the cause of error within the jar and create a minimal test case. We do not want to download the jar each time we execute our test pipeline.

2024-12-30 16:19 UTC, sahilagichani14 commented on sootup.java.bytecode.frontend/src/test/java/sootup/java/bytecode/frontend/inputlocation/FixJars.java
> +    String methodSignature =
kotlin code

2025-01-06 09:07 UTC, stschott requested changes

2025-01-06 09:07 UTC, stschott commented on sootup.java.bytecode.frontend/src/test/java/sootup/java/bytecode/frontend/inputlocation/FixJars.java
> +  public void executeaudiofileRCjar() {
Please remove this test. We only want to keep the isolated test version around. But also still keep the Maven coordinates of the original Jar around (maybe as a comment).

2025-01-06 09:17 UTC, sahilagichani14 commented on sootup.java.bytecode.frontend/src/test/java/sootup/java/bytecode/frontend/inputlocation/FixJars.java
> +  public void executeaudiofileRCjar() {
Can I @Disable this test? This test case fails locally but the pipeline is green, that's why I asked in the group.

![Uploading image.png…]()

2025-01-09 13:15 UTC, stschott approved these changes

2025-01-09 13:15 UTC, stschott commented on sootup.java.bytecode.frontend/src/test/java/sootup/java/bytecode/frontend/inputlocation/FixJars.java
> +  public void executeaudiofileRCjar() {
Can you investigate why this fails? Maybe due to the resolution of the artifact from Maven Central which might be cached on your machine or the pipeline?

2025-01-09 14:42 UTC, merged