Update AsmMethodSource.java
soot-oss/SootUp pull request #561
Opened 2023-03-28 08:42 UTC by Jacky-code519

The results should not be printed in the user's program

2023-03-29 15:08 UTC, JonasKlauke requested changes

2023-03-29 15:08 UTC, JonasKlauke commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java
> +      //instructions.iterator().forEachRemaining(item -> System.out.println(AsmUtil.toString(item)));
Thanks. Could you remove this line entirely? No need to comment it out.

2023-03-29 15:24 UTC, Jacky-code519 commented
@JonasKlauke I finished

2023-03-30 12:52 UTC, JonasKlauke approved these changes

2023-03-30 12:53 UTC, merged