InvokeArgumentValidator changes
soot-oss/SootUp pull request #865
Opened 2024-02-21 20:23 UTC by Momo-Not-Emo

1. Adapt InvokeArgumentValidator and add test cases. The original version primarily focuses on verifying the number of arguments. 
2. Implement argument type checking by including `rt.jar` in the analysis input locations, as the validator relies on typeHierarchy. Add a corresponding test case for this scenario.
3. Rectify a bug in `JavaIdentifierFactory.getBoxedType(...)` related to the int type. Replace the erroneous `java.lang.Int` with the correct type, which is `java.lang.Integer`.
4. Add support to check implicit conversion for primitive types.
5. Add a workaround check in `ArchiveBasedAnalysisInputLocation.getClassSource(...)` to avoid casting exception when passing an anonymous `ClassType` object which cannot be casted to `JavaClassType` directly.

2024-02-22 09:03 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        callee.getParameterTypes().size()) {
This condition is always false as they point to the same data - we need to get a SootMethod via the view.

2024-02-22 09:03 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +            }
An additional check for correct argument types (+inheritance - use the view.typehierarchy() ) would be nice, too.

2024-02-22 09:03 UTC, swissiety commented on sootup.tests/src/test/java/sootup/tests/validator/InvokeArgumentValidatorTest.java
> +            if (!aClass.isLibraryClass()) {
isLibraryClass check is not necessary as only an AnalysisInputLocation with SourceType.Application is added to the view

2024-02-22 09:03 UTC, swissiety commented on sootup.tests/src/test/java/sootup/tests/validator/InvokeArgumentValidatorTest.java
> +                                .get(),
you can simplify accessing the methodBody: `view.getMethod( view.getIdentifierFactory().parseMethod("<InvokeArgumentValidator: void invokeArgumentValidator_success()>") ).get().getBody()`

2024-02-22 16:30 UTC, Momo-Not-Emo commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        callee.getParameterTypes().size()) {
> This condition is always false as they point to the same data - we need to get a SootMethod via the view.

The condition is not always true. In the `testInvokeArgumentValidatorFailure` case, the Jimple statement `l1 = virtualinvoke l0.<InvokeArgumentValidator: java.lang.String join(int,java.lang.String)>(1)` is constructed. Here, `invExpr.getArgCount()` evaluates to 1 (indicating one argument passed) while `callee.getParameterTypes().size()` evaluates to 2 (indicating two arguments defined in the method signature). They point to different data.

2024-02-22 16:33 UTC, Momo-Not-Emo commented on sootup.tests/src/test/java/sootup/tests/validator/InvokeArgumentValidatorTest.java
> +            if (!aClass.isLibraryClass()) {
you are right. This code is copied from an existing validator test. I'll simplify it.

2024-02-22 16:59 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        callee.getParameterTypes().size()) {
I see - I was already thinking about the actual method definition and was confused that no retrieving of a method was done.

2024-02-23 09:48 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        if (argType != paramType && (!typeHierarchy.contains(paramType)
I am not sure the Typehierarchy can handle primitive type relations / BoxedType compatibility - maybe we have to do that seperately via [type promotion](https://docs.oracle.com/javase/specs/jls/se11/html/jls-5.html)

2024-02-23 09:48 UTC, swissiety commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ArchiveBasedAnalysisInputLocation.java
> +          javaClassType, archiveRoot, new AsmJavaClassProvider(view));
what happened here?

2024-02-23 09:48 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/JavaIdentifierFactory.java
> +      name = "integer";
lets add a getBoxedName() to the primitive types?

2024-02-23 17:53 UTC, Momo-Not-Emo commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ArchiveBasedAnalysisInputLocation.java
> +          javaClassType, archiveRoot, new AsmJavaClassProvider(view));
> what happened here?

It throws exception that an **anonymous** ClassType cannot be cast to JavaClassType:

```java
      ClassType classTypeFieldRefValidator =
                new ClassType() {
                    @Override
                    public boolean isBuiltInClass() {
                        return false;
                    }

                    @Override
                    public String getFullyQualifiedName() {
                        return "jimple.InvokeArgumentValidator";
                    }

                    @Override
                    public String getClassName() {
                        return "InvokeArgumentValidator";
                    }

                    @Override
                    public PackageName getPackageName() {
                        return new PackageName("jimple");
                    }
                };

       ....

        // rt.jar is required since the validator uses typeHierarchy
        DefaultRTJarAnalysisInputLocation defaultRTJarAnalysisInputLocation = new DefaultRTJarAnalysisInputLocation();
        jimpleView = new JimpleView(Arrays.asList(jimpleInputLocation, defaultRTJarAnalysisInputLocation));

        final Optional<SootClass> classSource1 = jimpleView.getClass(classTypeFieldRefValidator);
        assertFalse(classSource1.isPresent());
```

It will search for the `classTypeFieldRefValidator` within both application classes and library classes (rt.jar). Subsequently, it will prompt the casting exception.

In the SootUp class hierarchy, `ClassType` only has one specific type under it, which is `JavaClassType`. I've restricted the search to only look within the application classes. As a result, it won't send an anonymous  `ClassType` object to `ArchiveBasedAnalysisInputLocation` anymore. Should we keep this type check ?

2024-02-23 18:43 UTC, Momo-Not-Emo commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        if (argType != paramType && (!typeHierarchy.contains(paramType)
`Typehierarchy` doesn't consider "int" to be an instance of "Number", that's why I cast the primitive type to its boxed type in "getClassType(...)". 

Actually, in `Typehierarchy.isSubType(...)`, the comment says "subtyping applies to ReferenceTypes only". There is a `PrimitiveHierarchy` class, but its static method `isAncestor(...)` only checks the ancestor-relationship between two primitive types

2024-02-27 15:57 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        if (argType != paramType && (!typeHierarchy.contains(paramType)
But this does not handle cases like: `int` is used as an argument of a `double` parameter (while double -> int is not allowed implicitly) - we should not fail in these cases

2024-02-27 15:59 UTC, swissiety commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ArchiveBasedAnalysisInputLocation.java
> +          javaClassType, archiveRoot, new AsmJavaClassProvider(view));
We should address this issue in whole in another PR - please add a comment that this is a temporary hack

2024-02-27 21:10 UTC, Momo-Not-Emo commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        if (argType != paramType && (!typeHierarchy.contains(paramType)
> But this does not handle cases like: `int` is used as an argument of a `double` parameter (while double -> int is not allowed implicitly) - we should not fail in these cases

I have added implicit conversion checks

2024-02-28 13:59 UTC, JonasKlauke requested changes
Thanks for the help to improve SootUp 👍

2024-02-28 13:59 UTC, JonasKlauke commented on sootup.core/src/main/java/sootup/core/validation/InvokeArgumentValidator.java
> +                        ClassType argClassType = getClassType(identifierFactory, argType);
After the primitive type check the argument could still have the type: arraytype. You can not assume it is automatically a classtype.

2024-02-28 13:59 UTC, JonasKlauke commented on sootup.tests/src/test/resources/validator/jimple/InvokeArgumentValidator.jimple
> +
add a testcase for array types. Primitive type array, Classtype array and both cases also as multi-dimensional array

2024-02-28 13:59 UTC, JonasKlauke commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ArchiveBasedAnalysisInputLocation.java
> +      if (type instanceof JavaClassType)
What type do you get here in case of an anoynmous class?

2024-03-01 21:12 UTC, Momo-Not-Emo commented on sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ArchiveBasedAnalysisInputLocation.java
> +      if (type instanceof JavaClassType)
> What type do you get here in case of an anoynmous class?
```
 ClassType classTypeFieldRefValidator =  new ClassType() {...}. // implement the abstract methods
```
It is a ClassType object but not an instance of JavaClassType. I observed that this code has been removed in the current test code.

2025-05-13 01:26 UTC, closed without merging