Apk to jimple
soot-oss/SootUp pull request #888
Opened 2024-03-11 15:34 UTC by palaniappan1

2024-07-12 12:10 UTC, swissiety requested changes
thanks for your big contribution :) I have a little feedback for you..

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/test/java/ApkToDexTest.java
> +            "/Users/palaniappanmuthuraman/Documents/android-platforms",
local/absolute path to platform jars

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/test/java/ApkToDexTest.java
> +  //   As this test uses almost 200 APK's, I have in my local, so this test is not committed.
please cleanup ;)

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
> +  Path apk_path;
private final

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
> +              .getDexFromSource(new File(apk_path.toString()), api_version);
apk_path.toFile()?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
> +    return SourceType.Application;
in theory we have it configurable everywhere.. but I see no usecase to set it to Library - so i guess we can keep it that way.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
> +  //  public String getAndroidJarPath(String jars, String apk) {
cleanup; keeping getAndroidAPIVersion() / target sdk() seems reasonable - but refactor that weird getMaxAPIAvailable() stuff into a Utility class as it seems like it useful to automatically determine which runtimes we have - maybe create a subclass of the apkanalysisinputlocation with that code which chooses the best fitting runtime jar as this would segregate the responsibilities - while still beeing able to configure choose manually. -- btw is the runtime jar currently still necessary?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
please add a usage example to the docs/analysisinput.md

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/DexUtil.java
> +        if (Util.isByteCodeClassName(typeDescriptor)) {
are there situations where the condition is false?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/DexUtil.java
> +    return JavaIdentifierFactory.getInstance().getClassType(DexUtil.toQualifiedName(className));
the identifierfactory instance should come from the view

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/DexUtil.java
> +        }
if this is the only call where we call the second parameter != 0.. lets use a do-while loop and return in the other cases directly without the intermediary type assignment

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/DexUtil.java
> +        }
ouh this case can lead to null as well.. if that is copied from the bytecodefrontend please adapt it there as well

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/DexUtil.java
> +  }
as this is a code duplicate - lets move that method into the *Modifiers

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/Util.java
> +    return ((className.startsWith("L") || className.startsWith("["))
charAt(0) + caching?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/Util.java
> +  }
multiple uses? inline?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/Util/Util.java
> +  }
like the other comment for Modifiers - are 2 Util classes necessary?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexClassProvider.java
> +    // TODO : In soot, they wrote this. This code makes sense, but dont know where to add this or
it seems in soot it was a mechanism to make the input apk available to the sourcelocator of soot - we dont have that anymore - this is covered via the analysisinputlocation in sootup

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexClassSource.java
> +    return Optional.empty();
when does classInformation == null happen? maybe we should throw throw an exception?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexFileProvider.java
> +  private static final Comparator<DexContainer<? extends DexFile>> DEFAULT_PRIORITIZER =
lets move that comparator to the end of the file

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexLibWrapper.java
> +      // TODO Change the api_version to some common place
TODO: make it configurable starting from the AnalysisInputLocation

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexLibWrapper.java
> +          //                            // to be resolved
are we handling that? do we have a testcase that checks for it?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexMethod.java
> +      if (Util.Util.isByteCodeClassName(className)) {
see question above

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexMethodSource.java
> +    return null;
throw new UnsupportedOperation("TODO") exception

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexMethodSource.java
> +  }
duplicate?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexMethodSource.java
> +    //    String className = classType.getClassName();
cleanup

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/dexpler/DexResolver.java
> +public class DexResolver {
do we need that cache? i.e. it seems like we are giving a dexlibwrapper to the converted class?
is the given wrapper (and its memory) released at some point?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/AgetInstruction.java
> +        Jimple.newAssignStmt(l, jArrayRef, StmtPositionInfo.getNoStmtPositionInfo());
do we have access to line numbers?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/AputInstruction.java
> +      // TODO : Need to add one field (tag) with both getters and setters in the statement class
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/ArrayLengthInstruction.java
> +    body.add(assignStmt);
why/necessity of setStmt and add?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/CastInstruction.java
> +        throw new RuntimeException("Invalid Opcode: " + opcode);
IllegalState

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/BinopLitInstruction.java
> +        throw new RuntimeException("Invalid Opcode: " + opcode);
IllegalState

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/CmpInstruction.java
> +    Type type = null;
type seems to be unused? can we make use of the type at the local definition? otherwise lets comment the assignments for possible later use

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/ConditionalJumpInstruction.java
> +      setStmt(markerUnit);
still necessary? wouldnt it be enought to store the target address to a map and add the branchtarget after everything is resolved?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/ConstStringInstruction.java
> +        new StringConstant(s, JavaIdentifierFactory.getInstance().getType("java.lang.String"));
can we cache the jlString classType? (and getting the identifierfactory from the view)

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/DexLibAbstractInstruction.java
> +  protected List<Integer> getUsedRegistersNums(RegisterRangeInstruction instruction) {
depending on the usecase - does a Set make sense here?
lets precalculate the amount of elements in the returned collection

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/DexLibAbstractInstruction.java
> +    List<Integer> l = new ArrayList<Integer>();
lets give asize hint as well

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FieldInstruction.java
> +      // TODO : Dont know which local to use here, as of now using null which will throw an error
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +      firstAssign = Jimple.newNopStmt(StmtPositionInfo.getNoStmtPositionInfo());
lets investigate into that; or defer that question - so just log it or put an assertion and wait until someone complains ;-)

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +      throw new RuntimeException(
IllegalState

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +      firstAssign = Jimple.newNopStmt(StmtPositionInfo.getNoStmtPositionInfo());
same as above

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +          break; // there can't be more than one new
do we know something about the structure of the register values except from int? maybe a bitset is more efficient

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +        value = IntConstant.getInstance(1);
BooleanConstant?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/FillArrayDataInstruction.java
> +          "Invalid Array Type occured in FillArrayDataInstruction: " + elementType);
illegalstate

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/GotoInstruction.java
> +    setStmt(markerUnit);
as above

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/MethodInvocationInstruction.java
> +    // TODO check isIntertface by someother way
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/MethodInvocationInstruction.java
> +      }
move this check out of the loop

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/MethodInvocationInstruction.java
> +    return type.startsWith("J") || type.startsWith("D");
charAt(0) + reuse

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/MoveExceptionInstruction.java
> +          "Real type of this instruction has not been set or was already retyped: " + this);
IllegalState

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/NopInstruction.java
> +    // TODO: In one example, there comes NoOp Instruction after the return statement, dont know how
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/PackedSwitchInstruction.java
> +    //        body.addBranchingStmt(jSwitchStmt, Collections.singletonList(defaultTarget));
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/PseudoInstruction.java
> +      throw new RuntimeException("Error: dataFirstByte was not set!");
IllegalState ; more in this file

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/ReTypeableInstruction.java
> +public interface ReTypeableInstruction {
is this a possible solution to the commented/currenlty unused type assigned variable?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/SparseSwitchInstruction.java
> +    //        targets.add(defaultTarget);
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/SwitchInstruction.java
> +    markerUnit = Jimple.newNopStmt(StmtPositionInfo.getNoStmtPositionInfo());
.

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/main/AndroidVersionInfo.java
do we still need it? is it part of the commented code or a duplicate in the inputlocation?

2024-07-12 12:10 UTC, swissiety commented on sootup.apk.parser/src/main/java/main/TaggedInstruction.java
> +public abstract class TaggedInstruction extends DexLibAbstractInstruction {
we removed tags in sootup.. do we use the tags somewhere?

2024-07-12 12:10 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/graph/MutableBlockStmtGraph.java
please revert

2024-07-12 12:10 UTC, swissiety commented on sootup.core/src/main/java/sootup/core/model/Body.java
please revert

2024-07-12 12:10 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexDefUseAnalysis.java
> +public class DexDefUseAnalysis {
is it dex specific or would it make sense to move it to the analysis module?

2024-07-12 12:10 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexNumberTranformer.java
> +                    //                        usedAsFloatingPoint = examineBinopExpr(stmt);
block is empty?

2024-07-12 12:10 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexTransformer.java
> +        throw new RuntimeException("ERROR: not an assign statement: " + arrayStmt);
IllegalState

2024-07-12 12:10 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexTransformer.java
> +        if (r instanceof JFieldRef) {
ValueVisitor would make sense here to replace the ifelse tree

2024-07-19 06:26 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/dexpler/DexResolver.java
> +public class DexResolver {
To retrieve each and every class, we need to look into its details from the given dex file. The cache over there read the dex file only once and store all the contents of the class. So every time we request for the details of the class, lookup from the cache and return the information. In short, caching over there is necessary.

2024-07-19 06:30 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/instruction/AputInstruction.java
> +      // TODO : Need to add one field (tag) with both getters and setters in the statement class
Not needed anymore.

2024-07-19 06:32 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/instruction/ArrayLengthInstruction.java
> +    body.add(assignStmt);
setStmt() is to assign the jimple equivalent of the dex/bytecode statement. So I have a map to maintain for every given dex instruction its corresponding Jimple Statement. It helps me in easy lookup later (when doing dangling instructions or branching statements)

addStmt() is to assign to the method body.

In my defense, both are needed I think :)

2024-07-19 06:43 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/instruction/ConditionalJumpInstruction.java
> +      setStmt(markerUnit);
This is one such way of handling stuff. Old School technique :)

2024-07-19 06:53 UTC, swissiety commented on sootup.apk.parser/src/main/java/instruction/ArrayLengthInstruction.java
> +    body.add(assignStmt);
seems reasonable. Just as a suggestion to minimize the necessary code: you could iterate over your map of instr->stmt at the end of conversion and add then add the stmts to the body (not sure about the markerunit replacement implementation but replacing them in the body - which is a list by then - so has O(n) to find the item would not be necessary )

2024-07-19 08:34 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/instruction/NopInstruction.java
> +    // TODO: In one example, there comes NoOp Instruction after the return statement, dont know how
Handled.

2024-07-19 08:36 UTC, palaniappan1 commented on sootup.apk.parser/src/main/java/instruction/PackedSwitchInstruction.java
> +    //        body.addBranchingStmt(jSwitchStmt, Collections.singletonList(defaultTarget));
Handled when constructing branching statement

2024-07-19 08:46 UTC, palaniappan1 commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexNumberTranformer.java
> +                    //                        usedAsFloatingPoint = examineBinopExpr(stmt);
Unwanted check, so removed it now

2024-08-05 13:28 UTC, kadirayk commented on sootup.apk.parser/resources/stats_file.csv
why do we need this?

2024-08-05 13:30 UTC, kadirayk commented on sootup.apk.parser/src/main/java/DexBodyInterceptors.java
are the body interceptors okay so? Or will you decide which ones to activate later?

2024-08-21 14:54 UTC, kadirayk approved these changes

2024-08-21 15:32 UTC, swissiety approved these changes

2024-08-21 15:32 UTC, swissiety commented on sootup.java.core/src/main/java/sootup/java/core/interceptors/Dex/DexNullTransformer.java
> +        AbstractInvokeExpr invExpr = stmt.asInvokableStmt().getInvokeExpr().get();
please cache: `stmt.asInvokableStmt()`

2024-08-21 15:32 UTC, swissiety commented on sootup.apk.parser/src/main/java/ApkAnalysisInputLocation.java
>  public class ApkAnalysisInputLocation<J extends SootClass> implements AnalysisInputLocation {
generics have been removed from AnalysisInputLocation in the meantime

2024-08-21 16:15 UTC, swissiety approved these changes

2024-08-21 16:16 UTC, merged