Issue 988 type assigner
soot-oss/SootUp pull request #989
Opened 2024-07-18 16:13 UTC by sahilagichani14

2024-07-18 16:21 UTC, sahilagichani14 commented
This is the case when running type assigner without rt.jar and reaching a situation where no SuperClass of exception class could be found. So warn about no rt.jar present

2024-07-19 13:59 UTC, sahilagichani14 commented
dependent on the bug fix, issue-975-typeresolver. once issue fix 975 is merged this would also pass

2024-07-29 11:55 UTC, stschott requested changes

2024-07-29 11:55 UTC, stschott commented on sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java
> +          .filter(Files::isRegularFile)
Can we, instead of using a jar for the test case, use a source/class file pair so that one can check the corresponding source?

2024-07-29 14:23 UTC, JonasKlauke reviewed
mmh the testcase should test the warning, it should not be a visual test by the developer

2024-07-29 14:23 UTC, JonasKlauke commented on sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java
> +            System.out.println("Applying Type Assigner to jar " + jarFile);
remove the println from the test case

2024-07-29 14:23 UTC, JonasKlauke commented on sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java
> +              (path1, path2) -> {
is there a reason for sorting it?

2024-07-29 14:49 UTC, sahilagichani14 commented on sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java
> +              (path1, path2) -> {
No, first I was testing 10 jars so I sorted them but now will remove it 👍

2024-07-29 14:52 UTC, sahilagichani14 commented on sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java
> +            System.out.println("Applying Type Assigner to jar " + jarFile);
@JonasKlauke Umm okay I will add Memory Appender for testing logs. 👍

2024-07-31 11:36 UTC, stschott approved these changes

2024-07-31 11:36 UTC, merged