assign TopType to ObjectType at end of TypeAssigner
soot-oss/SootUp pull request #997
Opened 2024-07-28 12:51 UTC by sahilagichani14

assign TopType to ObjectType at the end of TypeAssigner so LocalNameStandardizer doesn't give exception after.

2024-07-29 11:58 UTC, stschott requested changes

2024-07-29 11:58 UTC, stschott commented on shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class
Please isolate the issue and provide a source/class file pair instead of a class from a different library.

2024-07-29 12:02 UTC, sahilagichani14 commented on shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class
I have added that test case as well, I will remove this class from a diff lib.

2024-07-29 14:24 UTC, JonasKlauke commented on shared-test-resources/TypeResolverTestSuite/Misc/Misc.java
> +    System.out.println(a);
remove println from the testcases. It unnecessary blows up the tests

2024-07-30 07:15 UTC, stschott approved these changes

2024-07-30 07:15 UTC, merged